export enum UserTypes {
    FETCH_USER_REQUEST = "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE = "FETCH_USER_FAILURE",
    REMOVE_USERS_ODDS = "REMOVE_USERS_ODDS",
    FILTER_USERS_BY_GENDER = "FILTER_USERS_BY_GENDER",
  }
  