export enum UserTypes {
    FETCH_USER_REQUEST = "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE = "FETCH_USER_FAILURE",
    REMOVE_ODDS = "REMOVE_ODDS",
    FILTER_GENDER = "FILTER_GENDER",
  }
  